// Code generated by github.com/nofun97/adobo, DO NOT EDIT.

package schema

// testdata
type JustDefs struct {
    Address *JustDefsDefsAddress `json:"address,omitempty" yaml:"address,omitempty"`
    Contact *JustDefsDefsPerson `json:"contact,omitempty" yaml:"contact,omitempty"`
}

type JustDefsDefsAddress struct {
    Street_name *string `json:"street_name,omitempty" yaml:"street_name,omitempty"`
    Street_number *string `json:"street_number,omitempty" yaml:"street_number,omitempty"`
}

type JustDefsDefsPerson struct {
    Father *JustDefsDefsPerson `json:"father,omitempty" yaml:"father,omitempty"`
    First_name string `json:"first_name,omitempty" yaml:"first_name,omitempty"`
    Last_name string `json:"last_name,omitempty" yaml:"last_name,omitempty"`
    Mother *JustDefsDefsPerson `json:"mother,omitempty" yaml:"mother,omitempty"`
}